[[commodities-and-tradeable-securities]]
Commodities and Tradeable Securities
-----------------------------------

This book will concern itself with assets the rights attached to which
are sufficiently standardized that their ownership can be transferred
without involvement of a lawyer. Generally the rights reduce to the
stream of income and, in the case of equities, voting. In practice
voting rights are difficult to exercise if exposure is obtained through
derivatives and so we are really concerned about assets which generate a
stream of income, of various degrees of uncertainty.

When an asset is sufficiently standardized it can be transferred via an
exchange.

[[what-is-an-asset]]
What is an asset?
-----------------

I think of an asset as something that generates a cash-flow at some
point in the future. Many assets produce a stream of income, such as
equities and bonds, but some, such as commodities produce just one, on
their salefootnote:[Commodities will generate a negative stream of
income, as generally there will be a warehousing cost.].

In this chapter I will restrict myself to _cash_ or ``spot'' or ``real''
assets: ones which, if you can travel to them, you can kick, or at least
handle them, in contrast to derivative assets, which are contracts the
price of which depends, in some very general way, on the price. 

Accounts have a very binary view of the world. If a company spend money, it is either going to create an asset, or incur an expense, in basic bookkeeping terms. Because, in some cases, it's a bit of both, accountants invented accruals and prepayments. 
The system works very well, if you know 'exactly' how long the asset will last but in general this is where company accounts start to require some subjective judgement.
Even an asset is created, it, in general, doesn't last forever, so expense transactions have to be created in subsequent years, which then have to be countered against the asset, in the form of a depreciation account.

To reliably value securities, it's necessary to look at a stream of cashflows. Converting the traditional accounting reports into this is a highly developed art, on which there are many excellent books written. One of the better ones is <<{{book.bibliography}}#security-analysis, Security Analysis>>.

[[seniority-of-obligations]]
Seniority of obligations
------------------------

As a basic distinction, a loan, whether a bond or not, is a promise to
pay a sum of money in the future, a share is the promise to pay what is
left over when the bondholders have been paid off. Of course, as with
all promises, things can go wrong, so from the point of view of the
bondholder, the nominal amount is the maximum amount of money that the
investor can expect to receive. The risk that the investor bears is that
the borrower fails to repay. 

// [reasons: list]

[[bonds]]
Bonds
-----

Bonds are tradable debt securities. Essentially they are standardized
loans which can be traded on an exchange. 
They represent a nominal liability for the issuer, and, of course, a nominal asset for the holder.
Bonds provide exposure to credit, inflation, forex (if denominated in a foreign currency).

Bonds are often traded in large denominations (maybe USD 10,000) and are frequently held to maturity by the (largely institutional) investor. Bonds are a huge asset class, providing the large bulk of all financing for businesses. Their terms can be complicated by the presence of options held by the issuer to redeem before the full term.

The risk associated with bonds depends exactly how much of a companies financing is provided by them. 
Bonds are cheaper for companies to issue, because they carry less risk. Bondholders will, in principle, only start to represent a credit risk once the equity funding of a company has become worthless. 

It is possible to view a bond as having a claim over all the assets of a company, but in combination with writing a put on the claim with a strike price equal to the redemption value of the bond. This way of looking at a bond is only useful for fairly 'distressed' issues, something I do not cover in this book.

// put something in the intro about not covering junk bonds?

[[credit]]
Credit
------

Credit is a general term for tradeable and non-tradeable debt. Economically speaking, credit is a superset of bonds, covered above, but without necessarily being tradeable. 

[[equities]]
Equities
--------

Most of this book will be about equities. Although a number of other asset classes are much more important than equities, in practice equities require much more detailed analysis than other asset classes. 
There are two ways to go about investing in equities. One is to do fundamental analysis of a company's business, using its published accounts, and any other publicly available information about the issuer. The other is to use more aggregated metrics to identify mis-valued equities by sector or country. This is the approach I have always used, and which I'll write about here.

Analysts and traders in individual equities perform a very valuable asset allocation function. 
If they their job probably they divert resourses to where they can produce the biggest return, 
and make a profit at the same time. 
The participants in this market also, by arbitraging away the mis-pricing, allow people like me to invest 
in a macro-driven way, without having to worry too much about valuation of individual equities that make up an index.

Of course analysts and auditors are far from infallible, and sometimes a completely true and fair view of a company's prospects is deliberately concealed in the way it reports its accounts.

[[commodities]]
Commodities
-----------

Commodities are basic materials than can be traded in highly standarized lots. 
They can reveal a lot about the economy, especially the state of health of the world economy. 
Prices tend to be subject to the effect of long-term global business cycles. In principle, knowing where we are in the cycle can allow traders to identify 'bull' and 'bear' markets, and execute successful long-term momentum trades. In practice it's more difficult than that, with a lot of noise superimposed on the cycle, with both supply and demand being subject to many random shocks.

It is always said that the price of high-grade copper is a good overall barometer of the health of the world economy, from which the future path of stock prices may be (partially) inferred. This leads to 'the red metal' being referred to as 'Dr Copper' on occasions. I have never been able to make any money by looking at price signals from copper or any other commodity, although I do read the commodities markets report most days.

It's not clear that, even if you do want an exposure to one or more commodities, you should buy them in the form of ETFs or futures. Arguably, buying a mining company, or an oil production or exploration company could give you a cheaper exposure.

[[real-estate]]
Real Estate
-----------



[[infrastructure]]
Infrastructure
--------------
