[[commodities-and-tradable-securities]]
Commodities and Tradable Securities
-----------------------------------

This book will concern itself with assets the rights attached to which
are sufficiently standardized that their ownership can be transferred
without involvement of a lawyer. Generally the rights reduce to the
stream of income and, in the case of equities, voting. In practice
voting rights are difficult to exercise if exposure is obtained through
derivatives and so we are really concerned about assets which generate a
stream of income, of various degrees of uncertainty.

When an asset is sufficiently standardized it can be transferred via an
exchange.

[[what-is-an-asset]]
What is an asset?
-----------------

I think of an asset as something that generates a cash-flow at some
point in the future. Many assets produce a stream of income, such as
equities and bonds, but some, such as commodities produce just one, on
their salefootnote:[Commodities will generate a negative stream of
income, as generally there will be a warehousing cost.].

In this chapter I will restrict myself to _cash_ or ``spot'' or ``real''
assets: ones which, if you can travel to them, you can kick, or at least
handle them, in contrast to derivative assets, which are contracts the
price of which depends, in some very general way, on the price

[[seniority-of-obligations]]
Seniority of obligations
------------------------

As a basic distinction, a loan, whether a bond or not, is a promise to
pay a sum of money in the future, a share is the promise to pay what is
left over when the bondholders have been paid off. Of course, as with
all promises, things can go wrong, so from the point of view of the
bondholder, the nominal amount is the maximum amount of money that the
investor can expect to receive. The risk that the investor bears is that
the borrower fails to repay. [reasons: list]

[[bonds]]
Bonds
-----

Bonds are tradable debt securities. Essentially they are standardized
loans which can be traded on an exchange.

[[credit]]
Credit
------

Credit is a general term for tradeable and non-tradeable

[[equities]]
Equities
--------

[[commodities]]
Commodities
-----------

[[real-estate]]
Real Estate
-----------

[[infrastructure]]
Infrastructure
--------------
