= Asset Classes

[[what-is-an-asset-class]]
What is an asset class?
-----------------------

The key difference between asset classes is the dominant risk factor to which they are exposed.
Investing is all about managing risk, and if the different drivers of risk can be isolated into different asset classes, managing that risk becomes much easier.
In practice, it is impossible to find investable securities which have zero exposure to all but one risk driver.
Bond prices depend on interest rates, but they will be exposed to commodity prices through interactions with the wider economy. Equity options mainly depend on underlying prices, but both directly and indirectly they are exposed to interest rates.
Controlling risk by chosing a mix of asset from different asset classes cannot be an exact science.

[[commodities-and-tradeable-securities]]
Commodities and Tradeable Securities
-----------------------------------

This book will concern itself with assets the rights attached to which
are sufficiently standardized that their ownership can be transferred
without involvement of a lawyer. Generally the rights reduce to the
stream of income and, in the case of equities, voting. In practice
voting rights are difficult to exercise if exposure is obtained through
derivatives and so we are really concerned about assets which generate a
stream of income, of various degrees of uncertainty.

When an asset is sufficiently standardized it can be transferred via an
exchange.

[[what-is-an-asset]]
What is an asset?
-----------------

I think of an asset as something that generates a cash-flow at some
point in the future. Many assets produce a stream of income, such as
equities and bonds, but some, such as commodities produce just one, on
their salefootnote:[Commodities will generate a negative stream of
income, as generally there will be a warehousing cost.].

In this chapter I will restrict myself to _cash_ or ``spot'' or ``real''
assets: ones which, if you can travel to them, you can kick, or at least
handle them, in contrast to derivative assets, which are contracts the
price of which depends, in some very general way, on the price. 

Accounts have a very binary view of the world. If a company spend money, it is either going to create an asset, or incur an expense, in basic bookkeeping terms. Because, in some cases, it's a bit of both, accountants invented accruals and prepayments. 
The system works very well, if you know 'exactly' how long the asset will last but in general this is where company accounts start to require some subjective judgement.
Even an asset is created, it, in general, doesn't last forever, so expense transactions have to be created in subsequent years, which then have to be countered against the asset, in the form of a depreciation account.

To reliably value securities, it's necessary to look at a stream of cashflows. Converting the traditional accounting reports into this is a highly developed art, on which there are many excellent books written. One of the better ones is <<{{book.bibliography}}#security-analysis, Security Analysis>>.

[[seniority-of-obligations]]
Seniority of obligations
------------------------

As a basic distinction, a loan, whether a bond or not, is a promise to
pay a sum of money in the future, a share is the promise to pay what is
left over when the bondholders have been paid off. Of course, as with
all promises, things can go wrong, so from the point of view of the
bondholder, the nominal amount is the maximum amount of money that the
investor can expect to receive. The risk that the investor bears is that
the borrower fails to repay. 

// [reasons: list]

[[bonds]]
Bonds
-----

Bonds are tradable debt securities. Essentially they are standardized
loans which can be traded on an exchange. 
They represent a nominal liability for the issuer, and, of course, a nominal asset for the holder.
Bonds provide exposure to credit, inflation, forex (if denominated in a foreign currency).

Bonds are often traded in large denominations (maybe USD 10,000) and are frequently held to maturity by the (largely institutional) investor. Bonds are a huge asset class, providing the large bulk of all financing for businesses. Their terms can be complicated by the presence of options held by the issuer to redeem before the full term.

The risk associated with bonds depends exactly how much of a companies financing is provided by them. 
Bonds are cheaper for companies to issue, because they carry less risk. Bondholders will, in principle, only start to represent a credit risk once the equity funding of a company has become worthless. 

It is possible to view a bond as having a claim over all the assets of a company, but in combination with writing a put on the claim with a strike price equal to the redemption value of the bond. This way of looking at a bond is only useful for fairly 'distressed' issues, something I do not cover in this book.

// put something in the intro about not covering junk bonds?

[[credit]]
Credit
------

Credit is a general term for tradeable and non-tradeable debt. Economically speaking, credit is a superset of bonds, covered above, but without necessarily being tradeable.

Many businesses are credit businesses. Banks, clearly, but also real estate, insurance, and even some businesses that appear, on the surface, to be simply engineering manufacturers. Credit risk is often written about as a distinct category of risk, but really it is strongly linked to economic risk. Recently a lot of high yield debt has suddenly become more risky because oil prices have finally started to drop from their elevated levels, causing the cashflow that underpinned the issuer's ability to service the debt to shrink. 

[[equities]]
Equities
--------

Most of this book will be about equities. Although a number of other asset classes are much more important than equities, in practice equities require much more detailed analysis than other asset classes. 
There are two ways to go about investing in equities. One is to do fundamental analysis of a company's business, using its published accounts, and any other publicly available information about the issuer. The other is to use more aggregated metrics to identify mis-valued equities by sector or country. This is the approach I have always used, and which I'll write about here.

Analysts and traders in individual equities perform a very valuable asset allocation function. 
If they their job probably they divert resourses to where they can produce the biggest return, 
and make a profit at the same time. 
The participants in this market also, by arbitraging away the mis-pricing, allow people like me to invest 
in a macro-driven way, without having to worry too much about valuation of individual equities that make up an index.

Of course analysts and auditors are far from infallible, and sometimes a completely true and fair view of a company's prospects is deliberately concealed in the way it reports its accounts.

Although on a company's balance sheet, equity is categorized separately from liabilities, in essence it is a liability, but one that is undated and on which there is no obligation to any particular service cost. A company comes into existence _ex nihilo_ having had all its assets funded from debt or equity investments. It forever remains valueless, once its obligations to its creditors and its shareholders have been finally discharged. This gives rise to the idea of the corporate veil: the idea that a company is just an agreement amongst providers of capital to a business to partition the risk, and reward, amongst themselves.  

Sadly, most governments do not quite see a company in this light, and find the veil somewhat opaque. They impose a tax on profits, at the company level, and then again on income paid out to bondholders and equity holders. For reasons which are far from clear to me, companies are permitted to treat debt service as an expense, but not income paid to shareholders (dividends). This creates considerable distortion, and the existence of very high gearing, especially in financial companies, which in turn leads to high levels of risk associated with investing in their equity.


[[commodities]]
Commodities
-----------

Commodities are basic materials than can be traded in highly standarized lots. 
They can reveal a lot about the economy, especially the state of health of the world economy. 
Prices tend to be subject to the effect of long-term global business cycles. In principle, knowing where we are in the cycle can allow traders to identify 'bull' and 'bear' markets, and execute successful long-term momentum trades. In practice it's more difficult than that, with a lot of noise superimposed on the cycle, with both supply and demand being subject to many random shocks.

It is always said that the price of high-grade copper is a good overall barometer of the health of the world economy, from which the future path of stock prices may be (partially) inferred. This leads to 'the red metal' being referred to as 'Dr Copper' on occasions. I have never been able to make any money by looking at price signals from copper or any other commodity, although I do read the commodities markets report most days.

It's not clear that, even if you do want an exposure to one or more commodities, you should buy them in the form of ETFs or futures. Arguably, buying a mining company, or an oil production or exploration company could give you a cheaper exposure.

[[real-estate]]
Real Estate
-----------
Real estate is an asset the supply of which reacts to demand only slowly, and with long lags. Obviously it may be held directly, and many individuals own the property they live in. This allows their house to have a hybrid function of being a store of wealth and a shelter. Usually the tax treatment of gains on houses is very generous, because otherwise this would be a very visible and unpopular tax.

Because borrowing to fund house purchase is common, residential property becomes the only geared investment the average person ever makes. This allows they to enjoy amplified returns when house prices appreciate, but, also, amplified losses when they go the other way. Although this is not the experience of so many British people, a lot of US investors were badly burned in the crash of 2008 and lost their homes, with consequences which are still being felt today.
 

Because of the double taxation problem mentioned under <<#commodities, Commodities>> there are problems with real estate companies issuing a lot of equity. Governments in various places have acknowledge this 


[[other-asset-classes]]
Other Asset Classes
-------------------

I do not accept that:

.	private equity,
.	hedge funds,
.	convertible bonds,
.	catastrophe bonds footnote:[Why Buffett is steering clear of catastrophe bonds, Gillian Tett, FT, 9 May 2014].  or
.   infrastructure

constitute separate asset classes, although I do not know enough about the last to be
completely confident. 


