[book]
title = "Investing"
author = "Steve H"
description = "How to lose money more slowly on the stockmarket."

[build]
build-dir = "risk-and-return-built"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
# additional-css = ["custom.css"]

[output.html.search]
limit-results = 15

# {
#     "plugins": [
#         "katex"
#     ],
#     "size": {
#         "w": 1800,
#         "h": 2360
#     },
#     "pluginsConfig": {},    
#     "author": "Steve Hemingway",
#     "background": {
#         "color": "#09F"
#     },
#     "font": {
#         "size": null,
#         "family": "Impact",
#         "color": "#FFF"
#     },
#     "structure": {
#         "readme": "README.md",
#         "summary": "SUMMARY.md"
#     },
#     "variables": {
#         "host": "gitbook.com",
#         "author_name": "Steve Hemingway",
#         "author_email": "steve.hemingway@gmail.com",
#         "best_brokerage": "Interactive Brokers",
#         "bibliography": "Appendices/bibliography.md"
#     },
#     "title": "Investing 101 (working title)",
#     "gitbook": ">=3.0.0"
# }