= December

This month was dire. My main exposure is to european stocks. 
They continued to sag as concerns over the middle east, Paris bombings,
Daesh, Russian involvement in Syria, Fed tightening, continued disappointing news coming out of China, and weak commodities prices, especially oil and iron, continued to be a daily feature of the news.

I took the view that all this was temporary and I could afford to buy on the dips, but the dips kept on dipping, and I was beginning to feel that the ZeroHedge view of the world was absolutely correct.

I had just read a book _The Complete Investor_ by Tren Griffin, about Charlie Munger, and his ideas about finding intrinsic value and nearly decided that I was doing it all wrong.

Fortunately, the Fed's tightening, which is about to be announced on the 16th seemed to concentrate everyone's minds on about the 14th. The conclusion of the market, tentatively, is that everything is going to be alright.

I am not out of the woods, but prices have strengthened promisingly.

I also bought a chunk of Valeant, (VRX), which did pretty well, but I chicked out on the 15th and closed the position at a decent profit. If I notice it dipping again, I plan to sell.

