= Derivatives

[[introduction]]
== Introduction

There are a lot of books on derivatives. There are a very large number
of books on the valuation of derivatives. This is a fascinating field of
study, and has resulted in work that has many [how many: list!] Nobel
prizes in recent years. A deep knowledge of economics and challenging
areas of mathematics such as Ito calculus and the solution of partial
differential equations is required to understand modern work on the
valuation of derivatives.

Fortunately it is very cheap and easy to obtain software that will
perform this valuation, and all that is really needed for trading is an
understanding of the independent (exogenous) variables that enter into
the valuation. The valuation of derivative securities is now so advanced
that it is almost inconceivable that an amateur investor could make
money by arbitraging derivatives which are mis-priced relative to their
underlying securities.

Derivatives have a role in amateur investing in the following ways:

1.  obtaining cheap exposure to securities that otherwise would be very
difficult for amateurs to trade, such as copper or pork bellies,
2.  converting income to capital gains, and otherwise to take advantage of differential tax  treatment for different types of profits or gains, (e.g. CFDs)
3. allowing trading at convenient times for an investor based away from the timezone where the underlying is trading (e.g. the XINA50 future, that trades during European and US timezones, on a Chinese equity index underlying),
4. standardizing exposure to a class of assets, such as government bonds, e.g. T Bill futures, where the underlyings have a range of coupons and maturity dates.


[[otc-and-exchange-traded-derivatives]]
== OTC and Exchange-Traded Derivatives

Increasing regulation of public stock exchanges have lead to the
creation of private platforms for trading a range of financial
securities. Public stock exchanges create a lot of value for providers
and consumers of capital. Companies get the best price for their new
issues, investors get the best price for securities they buy. Public
exchanges provide various investor protection services, in terms of
standardization and monitoring. These benefits are large, but when large
compliance costs imposed on those who use a public exchange reach a
threshold level, a private exchange, accessible only by large investors,
becomes a viable competitor. For FX, where there are relatively few
assets, which naturally need minimal standardization or monitoring, the
whole market became `OTC' many years ago. It seems likely that this will
happen more widely in the future.

Exchange-traded derivatives usually benefit from a clearing house
provision, which, for individual investors is indispensible. This means
that no investor is exposed to the credit risk of any other investor:
all trades are with a central counterparty that always executes `back to
back' trades so that it is never left with a net market exposure.

[[futures]]
== Futures

Futures allow the investor to gain an exposure to an underlying cheaply
and with very little contaminating risk, particularly if the near month
is traded. Buying a future is like buying the underlying, but giving up
a few months’ income, and pre-paying a few months’ financing cost.
Although a future gives an exposure only until its maturity date, it is
usually very cheap to `roll' the future into the next nearest delivery
month. 

This method can be used to give a long-term exposure to the
underlying, packaged up with the cheapest possible financing. For a
small scale investor, it is extremely important to minimize the cost of
finance. 
CFDs can produce the same exposure, and to a larger range of markets and sectors, but only at a cost of more expensive carry costs.


My own preference is to use futures to gain an exposure to an underlying, if a suitable contract is available. *Some* futures have poor liquidity, and short trading hours, but compared to even main market shares, the spreads are very low.  
It is more easy to get a fine-grained country or region exposure using futures than it is to get sectoral exposure. 
DTB offers contracts on all the sectors which make up the STOXX 600 index of European equities. 
An example of the sorts of sectors you can get an exposure to via futures using this method includes:

* insurance,
* construction and materials,
* chemicals,
* banks,
* travel and leisure.

Unfortunately, you cannot get within-country sector exposure with futures (banks in the UK) or even the more fine-grained exposure you might want (e.g. non-life insurance only). 

CFD/Spread betting providers will allow you to take a view on within-country sector exposure (certainly within the UK), but this is likely to come at a cost. [quantitative estimate based on IG account?]

As ever, there is going to be a tradeoff. A sector future will not have the liquidity of the whole market. For you to be able to buy there must be someone, somewhere, ready and willing to sell. Exchanges exist to allow buyers to find sellers, but sometimes there is just nobody to take the other side of a trade. Automation of trading does not help with this, unless traders abdicate control of their positions to an algorithm. Even if they did, the algorithm might be unwilling to take the other side of your trade.


[[swaps]]
== Swaps
Swaps are wonderful for switching an exposure to a particular maturity (e.g. 3-month floating rates) to another maturity (e.g. 10 year fixed). They also work well for foreign exchange. 

Institutional traders can trade equity swaps, which do the same sort of thing where one side of the exposure is an index. However, for the individual trader this is really not viable, mainly because to a large extent the sort of exposure switching you could achieve with a swap can be replicated using futures or CFDs.

This situation may change. Many products available only to the most sophisticated professional traders have found their way onto retail platforms over the years, and this may be another one about to be launched onto an unsuspecting public.

[[options]]
== Options

Options are like insurance policies. They pay out when something (more or less) unlikely happens.
In the happy world of securities trading you can not only buy the policy, but write it too. 
It's like having the option to be the bookie or the punter, to draw a parallel with the world of betting.

Basic options are puts and calls. The former pay out if the underlying's price drops below a fixed level. The latter if it exceeds a fixed level. 

[[example]]
=== Example

[[call-example]]
==== Call Example

If you have an inkling that a bid for Marks and Spencer may be launched in the next month you can buy a put, to allow you to profit if the price shoots up, without committing a lot of capital by buying the underlying, and without being exposed to any downside if the quarterly results are very dissapointing, or the Bank of England unexpectedly hikes interest rates.

If this all sounds too much like a free lunch, it is. You have to pay a premium, not unlike an insurance premium, to get this 'no downside risk' exposure. If the hoped-for bid fails to materialize you've incurred the cost without having anything but an expired policy to show for it.

[[put-example]]
==== Put Example
You have noticed that there is strong momentum in the S&P 500 index, and you don't want to miss the boat.
However, you notice that on a lot of fundamental valuation measures (market cap to GDP, price to book) the market is looking distinctly overvalued and you fear a large drawdown.

You decide that you will protect against the worst by buying out of the money puts. 
You buy puts which are 30% out of the money.

////
 put an expanded version of this example discussing choosing a strike 2.5SDs away, or with a delta
 of 0.05, or at a certain cost. Refer to the Dao of Investing
 (maybe you decide to choose the strike to be 2.5 standard deviations away from market
////


[[greeks]]
=== Greeks

[[spread-betting]]
== Spread Betting

Spread betting is unique to the UK. Because a CFD-like product can be
wrapped into what is, for tax purposes, a bet where the odds are not
fixed at the point of entering into the bet, they are very favourably
treated for tax purposes. The big problem is that the underlying price
is a price made by the spread betting brokerage, and therefore is not
guaranteed to track the underlying. The other problem is that the
implicit financing cost can be very high. The websites are structured to
encourage high gearing and heavy use of stop orders. Both of these, are,
in my book, tickets to oblivion.

[[cfds]]
== CFDs

CFDs or `Contracts for Difference' are relatively new products, mainly
aimed at the retail investor. They combine a traded underlying with 100%
finance. They are equivalent to a rolling forward. They have a number of
problems: the financing cost may be high, may be less than transparent,
and may vary according to the size of the position. Having said all
this, a CFD provided by a good brokerage, such as \{\{ best_brokerage
}}, can provide good, cheap, exposure to and underlying where other
methods would be prohibitive.

// []Highlight difference between synthetic and physical ETFs.]

[[etfs]]
== ETFs

ETFs, or Exchange Traded Funds, are a recent development which has
revolutionized investing in the last ten years or so. They are
securities, packaged by large financial houses such as iShares or
Blackrock, which track a huge range of asset classes. They are a huge
bonus for retail investors who want to have fine control on their asset
class exposures and are true believers in the EMH within national
stockmarkets.

ETFs are of two kinds. * Physical ETFs are funds which are invested in a
portfolio which tracks, as closely as possible within cost constraints,
a particular index (often one defined by MSCI). +
* Synthetic ETFs, where the issuer replicates the behaviour of the
underlying using swaps and futures, but guarantees a maximum tracking
error against the published index. [Check this: does the issuer really
guarantee a tracking error, or do you, as the investor, just get what
the issuer manages to achieve using it’s derivatives-based strategy?]

[[foreign-exchange]]
== Foreign Exchange

[[stock-market-index]]
== Stock Market Index

[[direct-holdings-of-cash-equities-with-margin-finance]]
== Direct holdings of cash equities with margin finance

Most US brokerages will lend against equity as collateral. However, it
is almost never worth taking advantage of this to increase gearing as
the rates available are, in my limited experience, atrocious. Especially
as the maximum gearing is usually very low. It is much better to use
CFDs, which bundle finance with the original trade, or, even better, use
futures, where the counterparty, in effect bundles the financing.
