= Glossary

== The Glossary

The corresponding (indented) definition.The corresponding (indented) definition.The ‘no magic in gearing’ theorem. States that, in a slightly idealized
	world in which there are no taxes on dividends, profits or bond
	interest. Most practitioners probably think that this is total rubbish,
	but I rather admire it.The idea that the price of a security reflects all publicly available
	information about it at all times.non performance of contract.Ross Goobey, 50’sRisk arising from the fact that the price of securities in the future is
a random variable.	The number of derivatives contract that have not been closed. E.g. a new
	futures contract starts trading, you buy 1 contract (‘lot’ ), by entering
into a trade with a [.term]counterparty who sells you the lot. At this point,
	if no other trades have taken place, you the open interest for this
	contract is exactly one. Open Interest is a stock, Volume is a
	flow.Real Estate Investment Trust. Tax-privileged corporate structure that
gives a relatively pure exposure to developed (completed) commercial and
residential real estate. Residential REITs have various problems to do
with tax.Trading volume, amount of stuff changing hands.The stock of securities held by an investor. I.e. your portfolio: the
set of things you own. Ownership is used in a legal, but otherwise vague
sense. Your position is also known as your holdings: the stuff you own!The price at which the supply and demand schedules for a security are in
balance. See also bid price, last price, offer price and NBBO.To understand the net return on a portfolio it is best to imagine
creating it ex-nihilo. To acquire assets it is then necessary to borrow,
typically by borrowing (shorting) your home currency, or some other
funding source. Although people do not always think about equity
porfolios this way, it is actually a useful way to think about whether
or not an investment really is worth making. It might sound good to hold
a share portfolio for a year and show a total return of 10%, but if
short-term interest rates are running at 12% it suddenly doesn’t sound
so smart any more.
Because the Yen was, for so long, the currency with the cheapest carry
cost, it became very common, and profitable, to put on a ‘Yen carry
trade’, which involves selling the Yen against (for example) the dollar.
Because the long asset has the higher yield, this was a profitable
trade. Clearly the danger is that the Yen goes up before the redemption
date. This is exactly what simple arbitrage considerations would leave
us to believe.Certain prices have mean reverting behaviour. Yields cannot go up, or
down, forever. Reversing a trend, though, can take a long, and variable,
time. I think that yields tend to mean revert, but it’s not clear if equity prices do so.The explanation of why gdp growth is so slow.

== Short selling

Selling stuff you don't already own. Creating an obligation to deliver the stuff at a fixed price in the future.