[[glossary]]
Glossary
--------

[[miller-mogdiliani-theorem]]
Miller Mogdiliani Theorem
~~~~~~~~~~~~~~~~~~~~~~~~~

The `no magic in gearing' theorem. States that, in a slightly idealized
world in which there are no taxes on dividends, profits or bond
interest. Most practitioners probably think that this is total rubbish,
but I rather admire it.

[[effecient-market-hypothesis]]
Effecient Market Hypothesis
~~~~~~~~~~~~~~~~~~~~~~~~~~~

The idea that the price of a security reflects all publically available
information about it at all times.

[[credit-risk]]
Credit Risk
~~~~~~~~~~~

non performance of contract.

[[cult-of-equity]]
Cult of Equity
~~~~~~~~~~~~~~

Ross Goobey, 50’s

[[market-risk]]
Market Risk
~~~~~~~~~~~

Risk arising from the fact that the price of securities in the future is
a random variable.

[[open-interest]]
Open Interest
~~~~~~~~~~~~~

The number of derivatives contract that have not been closed. E.g. a new
futures contract starts trading, you buy 1 contract (`lot'), by entering
into a trade with a counterparty who sells you the lot. At this point,
if no other trades have taken place, you the open interest for this
contract is exactly one. Open Interest is a __stock__, Volume is a
__flow__.

[[reits]]
REITS
~~~~~

Real Estate Investment Trust. Tax-privileged corporate structure that
gives a relatively pure exposure to developed (completed) commercial and
residential real estate. Residential REITs have various problems to do
with tax.

[[volume]]
Volume
~~~~~~

Trading volume, amount of stuff changing hands.

[[position]]
Position
~~~~~~~~

The stock of securities held by an investor. I.e. your portfolio: the
set of things you own. Ownership is used in a legal, but otherwise vague
sense. Your position is also known as your holdings: the stuff you own!

[[market-price]]
market price
~~~~~~~~~~~~

The price at which the supply and demand schedules for a security are in
balance. See also bid price, last price, offer price and NBBO.

[[position-1]]
position
~~~~~~~~

The amount of quantity of a particular security available to buy or
sell.

[[carry-cost]]
Carry Cost
~~~~~~~~~~

To understand the net return on a portfolio it is best to imagine
creating it ex-nihilo. To acquire assets it is then necessary to borrow,
typically by borrowing (shorting) your home currency, or some other
funding source. Although people do not always think about equity
porfolios this way, it is actually a useful way to think about whether
or not an investment really is worth making. It might sound good to hold
a share portfolio for a year and show a total return of 10%, but if
short-term interest rates are running at 12% it suddenly doesn’t sound
so smart any more.

Because the Yen was, for so long, the currency with the cheapest carry
cost, it became very common, and profitable, to put on a `Yen carry
trade', which involves selling the Yen against (for example) the dollar.
Because the long asset has the higher yield, this was a profitable
trade. Clearly the danger is that the Yen goes up before the redemption
date. This is exactly what simple arbitrage considerations would leave
us to believe.

[[mean-reversion]]
Mean Reversion
~~~~~~~~~~~~~~

Certain prices have mean reverting behaviour. Yields cannot go up, or
down, forever. Reversing a trend, though, can take a long, and variable,
time. Example: price (or yield) of a bond, over time.

[[secular-stagnation]]
Secular Stagnation
~~~~~~~~~~~~~~~~~~
