= Introduction

== Audience

The objective of this book is to tell you about how I invest, to tell you about a few of the successes and failure that I've had, so that you end up knowing a bit more about managing your own savings. 
It will not turn you into George Soros, or equip you to start your own hedge fund, but it should enlighten you about some of the options available to those with modest savings to get a bit better return on their savings.

You have to have a reasonable amount of capital to make it worth reading this book, if you measure the benefits in purely financial terms. If you have only a hundred pounds to invest, the extra return you make is simply not going to cover the opportunity cost of reading this book, let alone the cost of buying it. However, you never know when you might come into money, and you can at least sound financially well-informed to your friends, even if you are broke.

== Why Invest?

We all consume resources and nearly all of us produce resources. 
footnote:[Global savings equals global investment as an identity, in the sense that all production not for immediate consumption must be financed by somebody's saving, somewhere. This of course includes accumulation of inventories.]
The timings of our consumption and production may not synchronize well, which leads us to save, and sometimes to borrow, to allow our pattern of consumption to be better timed.
We may wish to consume more education or durable goods early in our lives, to enjoy benefits later.
We may wish to save some of what we produce in our prime for our old age.
We may wish to save for some specific future event: having children, going on holiday, buying a house.


All these give rise to different time horizons for our savings, and to different tolerances for risk.
Quantifying risk is a big subject in the context of investment: possibly the biggest of all, and I shall come back to it. This book focusses mainly on savings over the longer term, by which I mean around ten years or longer. Sometimes a short term requirement for funds can be met by borrowing, but for most individuals there is a big spread between the rate at which they can borrow, and the rate at which they can lend, which means that it's rarely possible to substitute borrowing for liquidation of an investment.

From a strict economic perspective, consumption is what matters, but I think that it's possible to derive a considerable benefit from having savings that are big enough to cover the cost of any 'rainy day' that fortune may throw at us. 
On the other hand, there is no point in saving so much out of one's income that life is a miserable struggle.

Finally, try to avoid being both a saver and a borrower at the same time. Although this is hard to avoid entirely, this is usually a bad choice because of the asymmetrical behaviour of the tax system (often you will pay tax in the returns from saving, but not save tax on the cost of borrowing). Also, the 'spread' between saving and borrowing rates usually means that it is very hard to beat the return you get by reducing your borrowing.


== Financial Assets

The biggest class of all, in terms of investable assets is real estate. 
For most people, their most valuable asset is their house. 
In the UK, and in many countries, there are various tax breaks which make home ownership 
highly privileged in the tax system. 
This is something to do with the idea that property owners make better citizens: a proposition that
has not, to my knowledge, have any empirical backing.

Having written this paragraph, I do not have any intention of writing about investing in real 
property. There are many books to help you with this. 
One thing I will say is that returns on residential real estate are generally much worse than those on a diversified equity portfolio over long timescales, in contrast to what many people believe.
[put reference to work of Robert Shiller here].

I will focus mainly on the big asset classes of equities and fixed income securities. I will spend a little time on commodities. However, I do not consider hedge funds, or private equity, or infrastructure, or foreign exchange, or venture capital, or art or wine as distinct asset classes.  These are either weighted averages of more basic asset classes, or just too difficult to value. 


I also do not consider the very short term investing. Ordinary investors do not have investment horizons measured in hours. I accept that it is possible to make money, if you are very good, by anticipating very 
short term fluctuations of supply and demand in markets for very liquid assets such as foreign exchange, or futures, but this is not investment in any sense I use the word.


== To get the most out of this book

Probably the most important advice I can give you is to not rush into anything. 
It is very unlikely that your analysis will have revealed a major mispricing of some security that
the world's hedgefund traders and investment banking analysts have collectively overlooked.

It is worth trading in small size, or even running a paper trading account for a while, to realize what can really happen in a live market. Beware however that markets can behave predictably for decades before suddenly misbehaving. It's easy to be lulled into a false sense of security.

It is also worth reading other authors, and a reputable source of news, such as the FT or the Economist. 

Warren Buffett and Charlie Munger have both written a lot of sense about investing. Although much of what they write relates to assessing individual equities, they write a lot of sense about investing in general.
Warren Buffett once wrote that we should be given a quota of just twenty investment decisions over our lifetime. Once we'd made these investments, we'd have to live with the consequences. I am not sure I could have lived with this discipline, but it is also the case that my worst investment performance periods have been associated with my losing my nerve and closing out, or reversing, positions I'd lost money on, to see those the price movements that caused those losses reverse as soon as I'd changed my mind.

////
Bottom line:

* keep fees low,
* don't follow the crowd,
* keep transactions to an absolute minimum,
* recognize that even if the market is not prefectly efficient, it's not far off,
* build up a position slowly: work with the short term trend to minimize the average cost.
////


== About Me

I have worked in and around securities markets for a long time. I have
had an interest in them for even longer. I first came across tradable
investment markets when I was working a computer games company, in the
80’s. I wrote a trading simulator to help train FX traders (and others).

For the last twenty years I’ve been investing my own money (and that of
some close associates). I have made a lot of mistakes. I have learned a
lot of things in the process. My goal in writing this book is to help
you avoid these mistakes, and maybe to make some new ones of your own.
With any luck they’ll be less costly than mine, at least in percentage
terms.

== Goals

I had no intention of writing a book which is a comprehensive overview
of how financial markets work. My goal is to tell you the least you need
to know to have a reasonable chance of losing your shirt when you start
trading.

This book is for people who are prepared to be moderately active in
their investing: doing a few trades a week, on average. There definitely
comes a point, quite quickly, when frequency of trading erodes returns,
but to ignore macro changes can also be expensive.

If you want a portfolio that you can just check once a year, you need to
get a very broad exposure to assets on as many dimensions as possible.
This book will help you understand why this is important, and how to
execute this strategy, but you can afford to ignore the sections on
futures and options.

I will try to explain why it is important to understand the drivers of risk, 
and, having understood them, how to get compensated to the fullest possible extent for bearing risk.


== Further Reading

I include in the bibliography a range of my favourites, but this is a
very incomplete list. I would suggest that you keep in touch with
markets on at least a weekly basis. Most newspapers have some
stockmarket coverage, but not many have a very good coverage of macro
trends. The Economist Finance and Economics section has some good
articles. As for daily papers, Financial Times and the Wall St Journal
are both good, but there are also many free Internet resources. I
recommend Seeking Alpha, and Bloomberg Business.

To get a good understanding of the principles of corporate finance it 
is well worth reading <<{{book.bibliography}}#brealey-and-myers, Brealey and Myers>> .

To get started on understanding derivatives look at <<{{book.bibliography}}#hull, Hull>>.

I am a huge fan of Warren Buffett, and his very long term approach to investing. 
However I do not recommend getting exposure to individual companies as I believe that it is practically impossible to find seriously under- (or over-) valued companies with enough liquidity to make Buffett's value investment style practical for the individual investor. This is not to say that he cannot execute this to produce superior returns. 
If you are a fan of Buffett, I would suggest that it is much more cost effective for you to get exposure to Berkshire Hathaway by buying its shares (or via various means involving derivatives that I discuss in [Chapter on Derivatives]) than by trying to out-analyse his team.


== Exclusions
////

real real estate,
credit
cash bonds
forestry?
art?
wine?

////


== How to read this book
////
Suggested order of chapters to read with notes on what can be skipped, linked to readers' experience  and interest.
////



