= Introduction

Managing investments used to be about poor people managing money for rich people. In the parable of the talents, (Matthew 25:14-30), the man hands pieces of silver to three of his servants, whose performance is, shall we say, variable. In the modern world, the servants have been replaced by the hedge fund managers, and the rich man is now the hard working salaried employee whose pension is being managed.

Ironically, although very few 'ordinary people' now own stocks or take any active role in managing their savings, it has never been easier to do this. No longer is it necessary to pay fat fees to a stockbroker to receive research on the performance of a stock. Everything is available for nothing on the internet, courtesy of Google, or Yahoo or one of many other information providers.

////
The objective of this book is to tell you about how I invest, to tell you about a few of the successes and failure that I've had, so that you end up knowing a bit more about managing your own savings. 
It will not turn you into George Soros, or equip you to start your own hedge fund, but it should enlighten you about some of the options available to those with modest savings to get a bit better return on their savings.

You have to have a reasonable amount of capital to make it worth reading this book, if you measure the benefits in purely financial terms. If you have only a hundred pounds to invest, the extra return you make is simply not going to cover the opportunity cost of reading this book, let alone the cost of buying it. However, you never know when you might come into money, and you can at least sound financially well-informed to your friends, even if you are broke.
////
== Why Invest?

We all consume resources and nearly all of us produce resources. 
footnote:[Global savings equals global investment as an identity, in the sense that all production not for immediate consumption must be financed by somebody's saving, somewhere. This of course includes accumulation of inventories.]
The timings of our consumption and production may not synchronize well, which leads us to save, and sometimes to borrow, to allow our pattern of consumption to be better timed.
We may wish to consume more education or durable goods early in our lives, to enjoy benefits later.
We may wish to save some of what we produce in our prime for our old age.
We may wish to save for some specific future event: having children, going on holiday, buying a house.


All these give rise to different time horizons for our savings, and to different tolerances for risk.
Quantifying risk is a big subject in the context of investment: possibly the biggest of all, and I shall come back to it. This book focusses mainly on savings over the longer term, by which I mean around ten years or longer. Sometimes a short term requirement for funds can be met by borrowing, but for most individuals there is a big spread between the rate at which they can borrow, and the rate at which they can lend, which means that it's rarely possible to substitute borrowing for liquidation of an investment.

From a strict economic perspective, consumption is what matters, but I think that it's possible to derive a considerable benefit from having savings that are big enough to cover the cost of any 'rainy day' that fortune may throw at us. 
On the other hand, there is no point in saving so much out of one's income that life is a miserable struggle.

Finally, try to avoid being both a saver and a borrower at the same time. Although this is hard to avoid entirely, this is usually a bad choice because of the asymmetrical behaviour of the tax system (often you will pay tax in the returns from saving, but not save tax on the cost of borrowing). Also, the 'spread' between saving and borrowing rates usually means that it is very hard to beat the return you get by reducing your borrowing.


