[[audience]]
Audience
--------

I wrote this book to help people make money. 
I believe that for many people, it's possible to get returns good enough to justify spending some time researching and thinking about their own trading.
I believe that this is not only profitable, but also is an interesting hobby.

I cover how to trade, i.e. the mechanics of chosing a trading account, and how to select the right stocks to buy and sell. 
 
[[how-to-invest]]
How to Invest
-------------

Investing means forgoing consumption today, to enjoy consumption in the future.
This tradeoff is something each person must decide about for himself.
The one thing that everyone can agree on is that, for a given amount of saving (non-consumption) today,
the more it delivers in terms of consumption tomorrow, the better.
The exact date of '`tomorrow`' will vary, but the inequality holds.
This book is about maximizing the return on the investment: i.e. the amount of consumption in the future.
The point of having a return is to dispose of it, however, either by spending it or giving it away.
Keynes was almost right when he wrote 'The sole purpose of economic activity is to consume.'


The biggest class of all, in terms of investable assets is real estate. 
For most people, their most valuable asset is their house. 
In the UK, and, I suspect that in many places, there are various tax breaks which make it highly advantageous to own one's own home. It is likely, but not certain, that investment in one's own home should be preferred 
over putting money into the stockmarket.

Although I discuss investing in this via REITs, I do not propose to
write anything about direct investment. There is a book to be written
about making money from investing directly in real estate, but this
isn’t it.

I also do not cover very short term '`day  trading`', or have anything much
to say about technical analysis. I am quite prepared to believe that it
is possible to make money from this sort of trading, but I have no idea
how it is done. 
It certainly feels as though there is definitely some kind of short term mean reversion in markets, 
and I have bought after a steep dip, and sold after a large rise (ideally with limit orders), 
but I cannot recommend this as a way to make systematic and steady profits.
It is also the sort of trading that would be very time consuming, and I try to avoid
spending more than an hour or so a day on my investing, ideally a lot less. 
And this will include reading the market reports in the FT or similar.


[[to-get-the-most-out-of-this-book]]
To get the most out of this book
--------------------------------

It is worth reading some of the background books, listed in the
bibliography if you are not familiar with direct investment in securities markets.
You should try to get an idea of what investing strategy you wish to pursue, and,
having decided that, how to execute it at minimum cost. 
A big theme of this book is how to get a chosen exposure to a market at the cheapest possible cost.
Most amateur investors loose much more money by incurring excessive fees than by bad stock picking.


[[about-me]]
About Me
--------

I have worked in and around securities markets for a long time. I have
had an interest in them for even longer. I first came across tradable
investment markets when I was working a computer games company, in the
80’s. I wrote a trading simulator to help train FX traders (and others).

For the last twenty years I’ve been investing my own money (and that of
some close associates). I have made a lot of mistakes. I have learned a
lot of things in the process. My goal in writing this book is to help
you avoid these mistakes, and maybe to make some new ones of your own.
With any luck they’ll be less costly than mine, at least in percentage
terms.

[[goals]]
Goals
-----

I had no intention of writing a book which is a comprehensive overview
of how financial markets work. My goal is to tell you the least you need
to know to have a reasonable chance of losing your shirt when you start
trading.

This book is for people who are prepared to be moderately active in
their investing: doing a few trades a week, on average. There definitely
comes a point, quite quickly, when frequency of trading erodes returns,
but to ignore macro changes can also be expensive.

If you want a portfolio that you can just check once a year, you need to
get a very broad exposure to assets on as many dimensions as possible.
This book will help you understand why this is important, and how to
execute this strategy, but you can afford to ignore the sections on
futures and options.

I will try to explain why it is important to understand the drivers of risk, 
and, having understood them, how to get compensated to the fullest possible extent for bearing risk.


[[further-reading]]
Further Reading
---------------

I include in the bibliography a range of my favourites, but this is a
very incomplete list. I would suggest that you keep in touch with
markets on at least a weekly basis. Most newspapers have some
stockmarket coverage, but not many have a very good coverage of macro
trends. The Economist Finance and Economics section has some good
articles. As for daily papers, Financial Times and the Wall St Journal
are both good, but there are also many free Internet resources. I
recommend Seeking Alpha, and Bloomberg Business.

To get a good understanding of the principles of corporate finance it 
is well worth reading <<{{book.bibliography}}#brealey-and-myers, Brealey and Myers>> .

To get started on understanding derivatives look at <<{{book.bibliography}}#Hull, Hull>>.

I am a huge fan of Warren Buffett, and his very long term approach to investing. 
However I do not recommend getting exposure to individual companies as I believe that it is practically impossible to find seriously under- (or over-) valued companies with enough liquidity to make Buffett's value investment style practical for the individual investor. This is not to say that he cannot execute this to produce superior returns. 
If you are a fan of Buffett, I would suggest that it is much more cost effective for you to get exposure to Berkshire Hathaway by buying its shares (or via various means involving derivatives that I discuss in [Chapter on Derivatives]) than by trying to out-analyse his team.


[[exclusions]]
Exclusions
----------


[[how-to-read-this-book]]
How to read this book
---------------------

// Suggested order of chapters to read with notes on what can be skipped, linked to readers' experience  and interest.




