[[audience]]
Audience
--------

I wrote this book as a primer for trading securities markets. The aim is
to cover `stocks and shares' (bonds and equities), but also derivatives
markets.

[[to-get-the-most-out-of-this-book]]
To get the most out of this book
--------------------------------

It is worth reading one of the background books, listed in the
bibliography.

[Rutterford, ``An Introduction to Stock Exchange Investment''],

[[background]]
Background
----------

I have worked in and around securities markets for a long time. I have
had an interest in them for even longer. I first came across tradable
investment markets when I was working a computer games company, in the
80’s. I wrote a trading simulator to help train FX traders (and others).

For the last twenty years I’ve been investing my own money (and that of
some close associates). I have made a lot of mistakes. I have learned a
lot of things in the process. My goal in writing this book is to help
you avoid these mistakes, and maybe to make some new ones of your own.
With any luck they’ll be less costly than mine, at least in percentage
terms.

[[goals]]
Goals
-----

I had no intention of writing a book which is a comprehensive overview
of how financial markets work. My goal is to tell you the least you need
to know to have a reasonable chance of losing your shirt when you start
trading.

This book is for people who are prepared to be moderately active in
their investing: doing a few trades a week, on average. There definitely
comes a point, quite quickly, when frequency of trading erodes returns,
but to ignore macro changes can also be expensive.

If you want a portfolio that you can just check once a year, you need to
get a very broad exposure to assets on as many dimensions as possible.
This book will help you understand why this is important, and how to
execute this strategy, but you can afford to ignore the sections on
futures and options.

[[further-reading]]
Further Reading
---------------

I include in the bibliography a range of my favourites, but this is a
very incomplete list. I would suggest that you keep in touch with
markets on at least a weekly basis. Most newspapers have some
stockmarket coverage, but not many have a very good coverage of macro
trends. The Economist Finance and Economics section has some good
articles. As for daily papers, Financial Times and the Wall St Journal
are both good, but there are also many free Internet resources. I
recommend Seeking Alpha, and Bloomberg Business.

[[exclusions]]
Exclusions
----------

Investing is spending money on any asset that is not immediately
consumed. It is perfectly possible to invest in a car or a house. This
book does not cover these sorts of investment decisions. It restricts
itself entirely to investments in tradable securities.

The biggest class of all, in terms of investable assets is real estate.
Although I discuss investing in this via REITs, I do not propose to
write anything about direct investment. There is a book to be written
about making money from investing directly in real estate, but this
isn’t it.

I also do not cover very short term `day' trading, or have anything much
to say about technical analysis. I am quite prepared to believe that it
is possible to make money from this sort of trading, but I have no idea
how it is done.

{% include "./copyright.adoc" %}
