= November 2015

I got cold feet and decided to move towards a more hedged equity position. I decided to short the US and go long Europe (in the form of the DJ600 and EST50). Unfortunately this was sortly after a major correction across the globe. So far the US, to which I am exposed via the S&P 500 index, using mini-futures, symbol ES, has roared back, slightly making a mockery of the idea that I'd be fully hedged against a major move in global equities. 

Altogether, these have not been a terribly happy month or two. One silver lining is that I decided that it'd be better that my cash was held in USD, rather than GBP. Mark Carney's recent caution about the timings of rate rises (week 1 or the month) has resulted in some gains on the FX front. This position was opened up for hedging, so I can't really take credit for it as a brilliant trading decision, but I won't send back the profits.

I have also been influenced by the research results of <<{{book.bibliography}}#star-capital, Star Capital>>

I have been reading <<{{book.bibliography}}#spitznagel, Spitznagel>> and have, as a result, been spending modest amounts of money on out of the money puts. I would have liked to buy puts on the SPX, but to reduce my margin requirements I have been buying them on the STOXX 50 (ESTX50) instead.

 

== Week 1 

This was OK, except that my long ZN/ short GBL position continued to be a drag. 
The position is probably a bit large, but it seems to me that the view is essentially correct, that Europe's economy will pick up a bit on the coat tails of the US's, and bond yields on the two continents will come into alignment.

So far, this has not proved to be the case.

Otherwise, equity markets seem to be recovering, so I am making money. Unfortunately because I am semi-hedged, with a net short position in US equities, the short SPY and short ES futures positions are dragging me down.


== Week 2

Starting 9 November.

The markets got spooked by slightly bad trade data coming out of China. I took the opportunity of closing out some of my short equities positions. The day was fairly ugly.

Generally I don't trade on rumour, but I decided to go long Valeant (VRX). This has absolutely imploded, on the slightly sharp practice of selling through its captive pharmacist. I went long late in the evening (UK) on Monday. There is a conference call due tomorrow. This is definitely not my style, but I decided that it was worth a small punt.

My long dollar position has done well. Mark Carney, BoE governor seems to be putting off raising rates, which is having the effect of lowering the currency.

Because I am very negative about the government in South Africa, I shorted the ZAR. I did this in small size, because I suspect that the currency has already gone very low, but at least with Janet Yellen saying that she really will increase USD rates, this should add a margin of safety.

I also have had a feeling in my gut that eastern european equities are undervalued. I tried to trade the ATXDE future, as a proxy, but Interactive Brokers seems not to support trading it.

Although a country's stock market and its currency are not closely correlated, out of desperation I went long some zloty, via a Globex future, to get some exposure to Poland. Poland and Czech Republic seem markets to watch, but unfortunately there seem to be no active futures markets in these countries. I guess that I should be grateful that there is a functioning stock market in ex-Communist regimes. Poland has the WIG20 index, and it is a great source of mystery why some enterprising exchange (DTB?) hasn't introduced a future on it.

=== Wednesday

The dollar has been strengthening, driving down the SPX and ZN, and driving down GBL, thus causing losses on my interest rate position.

My long europe, Japan equity positions have done well.

I have decided that it is too dangerous to stay long US equities so I've been gradually reducing my short SPY and ES positions. Even though this increases the risk of my position, it reduces my margin requirement. If ever there was an example of margin levels not reflecting risk this is it. US brokerages do not 'get' trading in the rest of the world!

=== Weekend 14 Nov
The market has been slip sliding away towards the weekend on the basis of slightly weaker figures coming out of Europe, and nothing much of encouragement coming out of China.

The dollar has now found a level. Commodities continue to drift down, in spite of various contrarian pundits saying that the time has now come to invest in oil.

There are some fairly crazy valuations of IT startups going on. The creators of Minecraft and of Candy Crush Saga seem to be worth many billions of Euros. This seems incomprehensible to me, but my track record of making money by going short on these sorts of bubble companies is not so good. Having cast adrift the anchor of valuation based on profits or balance sheet assets, it's all too easy for investor mania to take a shareprice to a point where short sellers cannot bear the pain before the shooting star plummets to earth.

=== 16th Nov
It was widely expected that the shootings and suicide bombings in Paris on Friday night would precipitate a heavy fall in the CAC40 and across Europe. Comparisons were being made with the sort of drop the SP500 saw after `9-11'. I admit that being long Europe, and long CAC40 in particular, I was braced for the open on Monday and, I confess, lost some sleep over the sort of losses I would suffer. It did occur to me that the attacks, although deeply shocking and incomprehensible, would not materially damage the productive capacity of the French economy. Of course, if they affected demand, by changing the behaviour of the French, this would be a different matter, but my feeling was that the French were made of sterner stuff. After all, they did give us the word _sang-froid_.

In fact, after a shaky start, the market opened significantly up, and remained strong all day. 
The pundits who had predicted a meltdown were proved comprehensively wrong. 
It's probably dangerous to ignore the pundits entirely, but this was a dramatic demonstration of how wrong they can be about the impact of news on the market. There was not, as far as I can tell, any major piece of economics news that would have had a strong countervailing effect to the news of the terrorist attacks.









