## November


=== Week 1 

This was OK, except that my long ZN/ short GBL position continued to be a drag. 
The position is probably a bit large, but it seems to me that the view is essentially correct, that Europe's economy will pick up a bit on the coat tails of the US's, and bond yields on the two continents will come into alignment.

So far, this has not proved to be the case.

Otherwise, equity markets seem to be recovering, so I am making money. Unfortunately because I am semi-hedged, with a net short position in US equities, the short SPY and short ES futures positions are dragging me down.


=== Week 2

Starting 9 November.

The markets got spooked by slightly bad trade data coming out of China. I took the opportunity of closing out some of my short equities positions. The day was fairly ugly.

Generally I don't trade on rumour, but I decided to go long Valeant (VRX). This has absolutely imploded, on the slightly sharp practice of selling through its captive pharmacist. I went long late in the evening (UK) on Monday. There is a conference call due tomorrow. This is definitely not my style, but I decided that it was worth a small punt.

My long dollar position has done well. Mark Carney, BoE governor seems to be putting off raising rates, which is having the effect of lowering the currency.

Because I am very negative about the government in South Africa, I shorted the ZAR. I did this in small size, because I suspect that the currency has already gone very low, but at least with Janet Yellen saying that she really will increase USD rates, this should add a margin of safety.









