= Passive Investing

By "`passive investing`" I mean letting someone else make the actual trading decisions.

Although this book is about _active_ investing, where the goal is to improve returns by a modicum of trading via an excecution-only broker, it is likely that most readers will read it for background information and continue to allow their savings to be managed by an agent.



All the principles of choosing assets continue to apply.

John Kay has produced a very good book about this sort of investing, and John Bogle has produced many.

== keep fees low

ETFs. 

== don't follow the crowd

== don't chop and change

Don't choose a fund manager who has a high turnover of investments, either.

== "`You can't buck the market`"

recognize that even if the market is not perfectly efficient, it's not far off,

Stats on active managers.



== Take it easy
build up a position slowly: work with the short term trend to minimize the average cost. 

Pound cost averaging.

== Focus on Asset Allocation

don't abdicate responsibility for asset allocation. 
If you don't feel competent to make your own decision, at least resist the temptation to invest in the currently most fashionable market. At the very least do not put all your eggs in one basket, and that includes your own national stockmarket. 

