= Investing-101

I have read many books on investing, but none of them really fully prepared me to trade securities and avoid losing money.
I am writing the book that I wish I had read when I started seriously investing in the mid 1990s.
I have decided to write this and make it available to the public even from the very early drafts. If you would like to be added as a collaborator then please contact me.
Note that the files for this book are kept as git repositories on both github and bitbucket. You can fork my source from either repository!

I have decided to write it on  http://www.gitbook.com[gitbook.com]. 
This is a very neat website that uses http://www.github.com[github] as storage.
At the moment I've decided to use the free GitHub service, which means that I must share my 
work with the world. You can view the book both on GitHub and GitBook. 

I have provided this book under a 
https://creativecommons.org/licenses/by-nc-nd/4.0/[Creative Commons
Non-Commercial, No-Derivatives Licence]. This means that you’re free to
download and share, but you must not sell it or change it and pass it
off as your own. You must attribute me as the author if you share.

I have written the text of this book in a lightweight markup language called http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc]. 
I am indebted to the authors of http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[this cribsheet]  footnote:[I've never actually used or installed asciidoctor - I just use the asciidoc processor that comes with gitbook] and also http://www.methods.co.nz/asciidoc/userguide.html[this one].

I have sprinkled the odd equation through the text. In order to make these look good, even if they do not actually illuminate the message very much, I've used latex, for which I've found http://www.personal.ceu.hu/tex/cookbook.html[this page of examples] very helpful. 
Don't be intimidated. 
Just read the words. 
No information is presented only in the equations: they are just to link up this text with more 
formal accounts.



== Acknowledgements

My interest in securities markets was first piqued by Paul Roth, whom I met at Psion, where I was working as a humble programmer. He had come to the company with the idea of developing a trading simulator. The idea was that pilots were starting to learn how to fly aeroplanes by using a flying simulator, 
because the cost of crashing a plane was so high, compared to the benefit of learning the controls.
The idea was that using a simulator was cheap, compared to crashing the bank. 
We never really did get the sales we were hoping for, but the simulator worked, after a fashion, and the experience of getting it to work hooked me on trying understand the magic of markets for the rest of my career.





{% include "copyright.adoc" %}

// doesn't work! include::copyright.adoc[]
