= Investing-101

I have read many books on investing, but none of them really fully prepared me to trade securities and avoid losing money.
I am writing the book that I wish I had read when I started seriously investing in the mid 1990s.
I have decided to write this and make it available to the public even from the very early drafts. If you would like to be added as a collaborator then please contact me.
Note that the files for this book are kept as git repositories on both github and bitbucket. You can fork my source from either repository!

I have decided to write it on  http://www.gitbook.com[gitbook.com]. 
This is a very neat website that uses http://www.github.com[github] as storage.
At the moment I've decided to use the free GitHub service, which means that I must share my 
work with the world. You can view the book both on GitHub and GitBook. 

I have provided this book under a 
https://creativecommons.org/licenses/by-nc-nd/4.0/[Creative Commons
Non-Commercial, No-Derivatives Licence]. This means that you’re free to
download and share, but you must not sell it or change it and pass it
off as your own. You must attribute me as the author if you share.

I have written the text of this book in a lightweight markup language called http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc]. 
I am indebted to the authors of http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[this cribsheet]  footnote:[I've never actually used or installed asciidoctor - I just use the asciidoc processor that comes with gitbook] and also http://www.methods.co.nz/asciidoc/userguide.html[this one].

I have sprinkled the odd equation through the text. In order to make these look good, even if they do not actually illuminate the message very much, I've used latex, for which I've found http://www.personal.ceu.hu/tex/cookbook.html[this page of examples] very helpful.

== Acknowledgements


{% include "copyright.adoc" %}

// doesn't work! include::copyright.adoc[]
