= About this book




Many studies have shown that a chimp with a dartboard can construct a portfolio which outperforms the average  the average fund manager. If you pay the chimp in bananas he'll virtually always outperform, after fees.
Nevertheless, most ordinary savers choose to hand over their savings to a professional.
This book is an attempt to allow you to make an informed decision about whether to accept the advice of your financial advisor at face value.

The key to a DIY approach to investing is an understanding of risk. There are two aspects of this. Minimising risk for a given return, and deciding on the correct tradeoff between risk and return for your own preferences. Saving is about trading current consumption for future consumption. Each of us has values our current consumption relative to our future consumption differently. Conventional economic theory argues that utility is derived only from consumption, but I actually think that we get utility from knowing that we have assets 'for a rainy day', i.e. current utility, as well as the utility we receive when we actually consume those assets, but I am straying into a territory where I have no expertise.

////

I will spend a lot of time talking about risk. Risk is one of those things that is difficult to quantify. We want to take less risk, but we don't want to do so at the cost of locking ourselves into permanently low returns. Although we 
I think this is because most people do not know how to set about the business of 
investing their savings. 
You probably think that you could probably do pretty well, but you are worried that there
is a small but possibly significant risk that you'll mess things up horribly,
and this is simply not a risk you want to take with the money that you need to support you 
in retirement.

I therefore put a lot of emphasis on risk. What it means, how to measure it, 
how it depends on the composition of a portfolio, how to invest in derivatives
without taking unacceptable risks, and how to reduce risk 
by buying options. Most of all, I explain what the drivers of portfolio risk are, and
how risk and return are inextricably  linked.
////

A lot of books about modern portfolio theory are very ... theoretical. They are full of probability distributions, efficient frontiers, correlations and covariances. I am going to steer well clear of this stuff. Stephen Hawkin once wrote that every equation in a book cuts its potential readship by half. I cannot afford more than a couple of equations before my potential readship shrinks just to my mother, so be reassured that I will avoid equations, or at least use them purely for decoration.


This book is written with the aim of allowing the do-it-yourself investor to compete on at least level terms with the professional. I am however  keenly aware that most people will still prefer to leave it to a professional manager. In these cases, this book will allow a customer to make a fully informed choice of provider. There are many good financial advisors, and many know a great deal about investment. But they can face conflicts of interest, which can, in rare cases, lead to them giving less-than-optimal financial advice.


I also have written it with the passive investor in mind. By gaining a deeper understanding of the 
investment process, the reader will be equipped to make a better choice of collective investment.
Rather than choosing a fund such as a OEIC based on advertising or a famous name investor, you will be able to choose one on the basis of investment strategy or exposure to specific risks. 

I have worked in finance most of my life, and have been an active investor for the past couple of decades. 
I have made plenty of mistakes, and have learned from them. 
Although experience is (still) the best teacher, my goal is to make this book come a close second.

I want to write the book that I wish I had read when I started seriously investing in the mid 1990s.
My goal is to make this a truly 'crowd sourced' book. I have invited some associates to collaborate, but I am looking for more people to do so. 
I do not expect you to write a chapter: just say when you find that an explanation is laboured, or unusually unclear. Just drop me a note to be added.


== Reusing excerpts from this book
I have provided this book under a 
https://creativecommons.org/licenses/by-nc-nd/4.0/[Creative Commons
Non-Commercial, No-Derivatives Licence]. This means that you’re free to
download and share, but you must not sell it or change it and pass it
off as your own. You must attribute me as the author if you share.

== For the technically minded
The files for this book are kept as git repositories on both github and bitbucket. You can fork my source from either repository!

Most of the actual writing is done on  http://www.gitbook.com[gitbook.com]. 
This is a very neat website that uses http://www.github.com[github] as storage.
However, I can set up a local repository and 'git pull' the source and work to my heart's content on local copy, offline, knowing that I can merge back into the master branch later. 

I  using the GitHub service for the actual remote storage of files.
I'm using the free version, which means that I have no option but to  share my 
work with the world. 
You can view the underling asciidoc files both on GitHub, but use Gitbook for a more friendly interface with the option to export to formats for offline reading (ebook and pdf).

As as a backup to the backup, I'm also keeping a copy on https://bitbucket.com[bitbucket], which seems to have some significant advantages as a git repository, according to people who understand git much better than I do.

I am not an expert on git. It does seem a much under-used technology, which has applications beyond pure source control for programmers, which is where it started. The combination of it, and ascii-based markup, is, I believe, a great way to write books collaboratively.


=== What this book is written in
I have written the text of this book in a lightweight markup language called http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc]. This is fairly self-explanatory, and looks like plain text with a bit of fairly straightforward
decoration. If you want to know more, I recommend  http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[this cribsheet]  footnote:[asciidoctor is a pretty cool Ruby application that can be run on Windows, but I recommend looking at the Chrome extension that allows viewing of asciidoc files directly in the browser. This does not require any software to be installed locally.] and also http://www.methods.co.nz/asciidoc/userguide.html[this one]. 
If you ask to collaborate, and use the online editor, where you can see the markup and display preview alongside each other in real time, you probably won't even need the cribsheet.

I have sprinkled the odd equation through the text. In order to make these look good, even if they do not actually illuminate the message very much, I've used latex, for which I've found http://www.personal.ceu.hu/tex/cookbook.html[this page of examples] very helpful. 
Don't be intimidated. 
Just read the words. 
No information is presented only in the equations: they are just to link up this text with more formal accounts.

== Acknowledgements

I was first introduced to a economic and mathematical approach to securities and derivatives markets by Paul Roth, whom I met at Psion. I remain eternally grateful for that introduction.

I am also grateful for Tim Fletcher, formerly of Natwest Capital Markets, who opened my eyes to the pricing of interest rate swaps and other fixed income derivatives.

I've worked with lots of quants and programmers and traders over the years. I'm too lazy to list them all here, but I am grateful for the insights they imparted to me.

Many authors have helped me to the limited level of understanding that I've reached. Some are listed in the bibliography. 

////
where I was working as a humble programmer. He had come to the company with the idea of developing a trading simulator. The idea was that pilots were starting to learn how to fly aeroplanes by using a flying simulator, 
because the cost of crashing a plane was so high, compared to the benefit of learning the controls.
The idea was that using a simulator was cheap, compared to crashing the bank. 
We never really did get the sales we were hoping for, but the simulator worked, after a fashion, and the experience of getting it to work hooked me on trying understand the magic of markets for the rest of my career.
////


// doesn't work! include::copyright.adoc[]
