[[investing-101]]
Investing-101
-------------

I have read many books on investing, but none of them really fully prepared me to trade securities and avoid losing money.
I am writing the book that I wish I had read when I started seriously investing in the mid 1990s.
This is a very early draft of the book. 

I have decided to write it on  http://www.gitbook.com[gitbook.com]. 
This is a very neat website that uses [http://www.github.com]github as storage.
At the moment I've decided to use the free GitHub service, which means that I must share my 
work with the world. You can view the book both on GitHub and GitBook. 
If you are on GitHub you'll have a better experience by going to GitBook where the book can be accessed in
all sorts of useful ways. 
http://stevehem.gitbooks.io/investing-101/[Here is my book on gitbook].

I have provided this book under a 
https://creativecommons.org/licenses/by-nc-nd/4.0/[Creative Commons
Non-Commercial, No-Derivatives Licence]. This means that you’re free to
download and share, but you must not sell it or change it and pass it
off as your own. You must attribute me as the author if you share.

{% include "copyright.adoc" %}

// doesn't work! include::copyright.adoc[]
