= Investing-101

I have read many books on investing, but none of them really fully prepared me to trade securities and avoid losing money.
I want to write the book that I wish I had read when I started seriously investing in the mid 1990s.
My goal is to make this a truly 'crowd sourced' book. I have invited some associates to collaborate, but I am looking for more people to do so. 
I do not expect you to write a chapter: just say when you find that an explanation is laboured, or unusually unclear. Just drop me a note to be added.

== For the technically minded
The files for this book are kept as git repositories on both github and bitbucket. You can fork my source from either repository!

Most of the actual writing is done on  http://www.gitbook.com[gitbook.com]. 
This is a very neat website that uses http://www.github.com[github] as storage.
However, I can set up a local repository and 'git pull' the source and work to my heart's content on local copy, offline, knowing that I can merge back into the master branch later. 

I  using the GitHub service for the actual remote storage of files.
I'm using the free version, which means that I have no option but to  share my 
work with the world. 
You can view the underling asciidoc files both on GitHub, but use Gitbook for a more friendly interface with the option to export to formats for offline reading (ebook and pdf).

As as a backup to the backup, I'm also keeping a copy on https://bitbucket.com[bitbucket], which seems to have some significant advantages as a git repository, according to people who understand git much better than I do.

=== What this book is written in
I have written the text of this book in a lightweight markup language called http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc]. This is fairly self-explanatory, and looks like plain text with a bit of fairly straightforward
decoration. If you want to know more, I recommend  http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[this cribsheet]  footnote:[I've never actually used or installed asciidoctor - I just use the asciidoc processor that comes with gitbook] and also http://www.methods.co.nz/asciidoc/userguide.html[this one]. 
If you ask to collaborate, and use the online editor, where you can see the markup and display preview alongside each other in real time, you probably won't even need the cribsheet.

I have sprinkled the odd equation through the text. In order to make these look good, even if they do not actually illuminate the message very much, I've used latex, for which I've found http://www.personal.ceu.hu/tex/cookbook.html[this page of examples] very helpful. 
Don't be intimidated. 
Just read the words. 
No information is presented only in the equations: they are just to link up this text with more formal accounts.


== Stealing my work
I have provided this book under a 
https://creativecommons.org/licenses/by-nc-nd/4.0/[Creative Commons
Non-Commercial, No-Derivatives Licence]. This means that you’re free to
download and share, but you must not sell it or change it and pass it
off as your own. You must attribute me as the author if you share.



== Acknowledgements

I was first introduced to a economic and mathematical approach to securities and derivatives markets by Paul Roth, whom I met at Psion. I remain eternally grateful for that introduction.

I've worked with lots of quants and programmers and traders over the years. I'm too lazy to list them all here, but I am grateful for the insights they imparted to me.

Many authors have helped me to the limited level of understanding that I've reached. Some are listed in the bibliography. 

////
where I was working as a humble programmer. He had come to the company with the idea of developing a trading simulator. The idea was that pilots were starting to learn how to fly aeroplanes by using a flying simulator, 
because the cost of crashing a plane was so high, compared to the benefit of learning the controls.
The idea was that using a simulator was cheap, compared to crashing the bank. 
We never really did get the sales we were hoping for, but the simulator worked, after a fashion, and the experience of getting it to work hooked me on trying understand the magic of markets for the rest of my career.
////




{% include "copyright.adoc" %}

// doesn't work! include::copyright.adoc[]
