[[valuation]]
Valuation
---------

If you buy an asset that is under priced you will make money when it
becomes correctly priced. There are two problems with this: arriving at
the _correct_ price, and knowing when the market price will revert to
it. The assumption that the clearing price is not _correct_ which is
problematic. What is even more problematic, is that the demand and
supply shedule will adjust itself in some finite timescale. Somehow.

[[asset-classes]]
Asset Classes
-------------

[[equities]]
Equities
~~~~~~~~

[[valuation-comparables]]
Valuation Comparables
^^^^^^^^^^^^^^^^^^^^^

[[market-cap-to-gdp]]
Market Cap to GDP
+++++++++++++++++

The natural question to ask about whether a market is overpriced is
`compared to what?'. A lot of valuation metrics arise from various
plausible answers to this question. One answer is `compared to the
economy as a whole'. This is, supposedly, a favourite metric of Warren
Buffett. It certainly has the advantage of simplicity. The downside is
that it does not look at the shift in companies’ preferred financing
strategies. Over time, and between countries, companies finance their
capital spending in different ways. Investors’ enthusiasm for equities
has resulted in substitution of equity for debt. This certainly happened
in the 60’s, and is, arguably, happening now. In continental Europe,
even large companies choose bank debt over securities and especially
over equity, which is regarded as `Anglo Saxon capitalism'.

http://www.advisorperspectives.com/dshort/updates/Market-Cap-to-GDP.php,[This
article] gives some recent figures. Currently this indicator is
`flashing red' for long positions in equities.

[[equities-as-a-call-option]]
Equities as a call option
^^^^^^^^^^^^^^^^^^^^^^^^^

[[small-cap]]
Small Cap
^^^^^^^^^

[[large-cap]]
Large Cap
^^^^^^^^^

[mega cap?]

[[bonds]]
Bonds
~~~~~

[[corporate-bonds]]
Corporate Bonds
^^^^^^^^^^^^^^^

[[sovereign-bonds]]
Sovereign Bonds
^^^^^^^^^^^^^^^

[[fx]]
FX
~~

[[commodities]]
Commodities
~~~~~~~~~~~

[[real-estate]]
Real Estate
~~~~~~~~~~~

[[all-weather-portfolios]]
`All Weather' Portfolios
~~~~~~~~~~~~~~~~~~~~~~~~
