[[how-to-value-stuff]]
How to value stuff
==================

This is a good chapter to start with.

[[valuation]]
Valuation
---------

If you buy an asset that is under priced you will make money when it
becomes correctly priced. There are two problems with this: arriving at
the _correct_ price, and knowing when the market price will revert to
it. The assumption that the clearing price is not _correct_ which is
problematic. What is even more problematic, is that the demand and
supply schedule will adjust itself in some finite timescale. Somehow.

[[asset-classes]]
Asset Classes
-------------

[[equities]]
Equities
~~~~~~~~

A limited liability company is a wonderful invention, one of the many dreamt up by the Victorians.
I think that they did exist earlier, but because of the catastrophe of the South Sea Bubble, limited liability companies 
were effectively banned in the UK for a long time. 
// Need to check this!
Setting up a company allows creditors to take more or less risk, in exchange for more or less return. 


[[valuation-comparables]]
Valuation Comparables
^^^^^^^^^^^^^^^^^^^^^

[[market-cap-to-gdp]]
Market Cap to GDP
+++++++++++++++++

The natural question to ask about whether a market is overpriced is
'`compared to what?`'. A lot of valuation metrics arise from various
plausible answers to this question. One answer is '`compared to the
economy as a whole`'. This is, supposedly, a favourite metric of Warren
Buffett. It certainly has the advantage of simplicity. The downside is
that it does not look at the shift in companies’ preferred financing
strategies. Over time, and between countries, companies finance their
capital spending in different ways. Investors’ enthusiasm for equities
has resulted in substitution of equity for debt. This certainly happened
in the 60’s, and is, arguably, happening now. In continental Europe,
even large companies choose bank debt over securities and especially
over equity, which is regarded as '`Anglo Saxon capitalism`'.

http://www.advisorperspectives.com/dshort/updates/Market-Cap-to-GDP.php,[This
article] gives some recent figures. Currently this indicator is
'`flashing red`' for long positions in equities.

The problem with a lot of equities valuation is the noise caused by the business cycle. 
The well-known Shiller CAPE attempts to do this by looking back over ten years of earnings,
to average out some of the noise.
A more sophisticated attempt is http://www.advisorperspectives.com/dshort/guest/Easterling-So-Many-Choices-Part-1.php[the Crestmont P/E]. 
This produces a less noisy signal, but this is at the cost of bringing in more difficult-to-measure parameters.
In a situation where its impossible to be completely sure that the noise is at an acceptable level, it is best to use as wide a range of indicators, ideally ones which use totally independent statistics. 
// Ali, can you have a look a this?


[[equities-as-a-call-option]]
Equities as a call option
^^^^^^^^^^^^^^^^^^^^^^^^^

[[small-cap]]
Small Cap
^^^^^^^^^

[[large-cap]]
Large Cap
^^^^^^^^^

[mega cap?]

[[bonds]]
Bonds
~~~~~

[[corporate-bonds]]
Corporate Bonds
^^^^^^^^^^^^^^^

[[sovereign-bonds]]
Sovereign Bonds
^^^^^^^^^^^^^^^

[[fx]]
FX
~~

[[commodities]]
Commodities
~~~~~~~~~~~

[[real-estate]]
Real Estate
~~~~~~~~~~~

[[all-weather-portfolios]]
All Weather' Portfolios
~~~~~~~~~~~~~~~~~~~~~~~
